Adding savefigure
Queens-Physics/qexpy pull request #52
Opened 2020-10-29 14:44 UTC by guiguem

Added savefig method as a wrapper around the matplotlib one.
I am not sure about the syntax and conventions, so please correct me if I get it wrong.
From my tests this seems to work just fine...

2020-10-29 14:53 UTC, astralcai commented
> Added savefig method as a wrapper around the matplotlib one.
> I am not sure about the syntax and conventions, so please correct me if I get it wrong.
> From my tests this seems to work just fine...

Please check your code with pylint first, or just check the tests. It seems to think that you have an extra white space somewhere.

2020-11-03 16:40 UTC, astralcai commented on qexpy/plotting/plotting.py
> +            self.main_ax.legend()  # show legend if requested
put all this in a separate method and call from both this and show()

2020-12-14 08:23 UTC, guiguem commented on qexpy/plotting/plotting.py
> +            self.main_ax.legend()  # show legend if requested
I think I fixed the errors and implemented the method you mentionned.

2020-12-14 23:00 UTC, astralcai commented on qexpy/plotting/plotting.py
> +    def savefig(self, filename):
You should add **kwargs to the argument, and pass these arguments directly to the pyplot savefig function, this way users are free to specify stuff like DPI and colour. So it would be

```def savefig(self, filename, **kwargs)```

and then on the last line

```plt.savefig(filename, **kwags)```.

Do this for both instances of savefig.

2020-12-14 23:01 UTC, astralcai requested changes
One last change to be made I think, I put the comment in the code.

2020-12-28 18:40 UTC, merged